name: launch
version: 0.1.0.0
synopsis: Launcher based around FZF
description: Please see the README at <https://github.com/jwoudenberg/launch>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2021 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/launch#readme
license-file: LICENSE
category: Web
github: jwoudenberg/launch
extra-doc-files:
- README.md
library:
  exposed-modules:
  - Launch
  source-dirs: src
executables:
  launch:
    dependencies:
    - launch
    main: Main.hs
    source-dirs: app
dependencies:
- base >= 4.10.1.0 && < 5
- bytestring >= 0.10.8.2 && < 0.12
- text >= 1.2.3.0 && < 1.3
- containers >= 0.6.0.1 && < 0.7
- conduit >= 1.3.0 && < 1.4
- conduit-extra >= 1.3.0 && < 1.4
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- StrictData
